# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7a18fac53573c0a96cc711c0eb652506efbe3d2f4e810ce9ed6a4d27668b39eb0e565c72d35da8706f59d874e067a4351897d156a1fd9a26b225d89ca46b00ee

test:
  secret_key_base: f4690a513124c9a2fdcafb8f8b293543b6db4ce70449a1117a9560b0fd52d3141438fb744500878c4b2820242a7c2ce6eb45c0639660caa99a54b21c92c3efa8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
